### ISSUE TITLE
bootstrap.sh can't support Unix.

### ISSUE THREAD

**Issue by meijifei** [DeemOpen/zkui#70]
I think docker/bootstrap.sh is written in Windows.  
I build it then run it:   
```
docker build -t zkui:2.0 .
docker-compose up -d zkui
```  
 then run it, it report errors. `/bin/sh^M: bad interpreter: No such file or directory`  
this is my docker-compose.yaml
```
version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.13
    restart: always
    ports:
      - "2181:2181"
  zkui:
    image: zkui:2.0
    ports:
      - "9090:9090"
    environment:
      - ZK_SERVER=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
```
I have solve this problem, I rewrote bootstrap.sh in Linux.
